### ISSUE TITLE
test deconv 3d fails

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-warp#3]
```
[   FAILED ] TestDeconvolve3D.test_run


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-warp/warp/tests/test_protocols_tomo.py", line 105, in test_run
    self.assertSetSize(outputTomos, 4)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 224, in assertSetSize
    self.assertEqual(setObjSize, size)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 4

```

**Comment by azazellochg** [comment]
can't reproduce this. check if your imod plugin is up to date

**Comment by MohamadHarastani** [comment]
I will try to reproduce it on another computer right now

**Comment by MohamadHarastani** [comment]
Reproduced on another computer right away. In the runstd.err I see a warning, but I am not sure if that is relevant.
```
00001:   /home/harastam/scipion3/scipion-em-warp/warp/utils.py:101: RuntimeWarning: divide by zero encountered in true_divide
00002:     wiener = ctf / (ctf * ctf + np.divide(1, snr))
```

**Comment by azazellochg** [comment]
You are not using the latest code from devel branch.

**Comment by MohamadHarastani** [comment]
You are right about the devel branch! The warning is gone. But the test still fails.

**Comment by MohamadHarastani** [comment]
There is no problem other than there are only two tilt series in the test data tutorialDataSusan and the assert is looking for 4 tomograms.. check your local ~/scipion3/data/tests/tutorialDataSusan/
Here is what I see
![image](https://user-images.githubusercontent.com/45387413/203060384-e2c0ed43-c165-46e7-9daa-c24ca4027e11.png)

**Comment by azazellochg** [comment]
aah, you are right. I think I have added more files to my folder for development reason. I'll fix the test
